version: "2.1"
services:
    odoo:
        build:
            context: ./odoo
            args:
                # To aggregate in development, use `setup-devel.yaml`
                AGGREGATE: "false"
                # No need for this in development
                CLEAN: "false"
                COMPILE: "false"
                CONFIG_BUILD: "false"
                ODOO_VERSION: "12.0"
                PIP_INSTALL_ODOO: "false"
        environment:
            ADMIN_PASSWORD: admin
            DOODBA_ENVIRONMENT: devel
            INITIAL_LANG: "fr_FR"
            PYTHONOPTIMIZE: ""
            PGDATABASE: dev12
            PGPASSWORD: pgpass
            PGUSER: odoo
            PROXY_MODE: "false"
            PYTHONPATH: /opt/odoo/custom/src/odoo
            SMTP_PORT: "1025"
            # You may want demo for development
            WITHOUT_DEMO: "false"
        tty: true
        ports:
            - "127.0.0.1:8069:8069"
            - "127.0.0.1:6899:6899"
        depends_on:
            - db
            - smtp
            - wdb
        volumes:
            - ./odoo/custom:/opt/odoo/custom:ro,z
            - ./odoo/auto/addons:/opt/odoo/auto/addons:rw,z
            - filestore:/var/lib/odoo:z
        command:
            - odoo
            - --workers=0
            - --init=base
            - --dev=reload,qweb,werkzeug,xml,wdb

    db:
        image: postgres:10-alpine
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: pgpass
            POSTGRES_DB: dev12
        volumes:
            - db:/var/lib/postgresql/data:z
        command:
            - -cwork_mem=32MB

    smtp:
        image: mailhog/mailhog
        ports:
            - "127.0.0.1:8025:8025"

    wdb:
        image: yajo/wdb-server
        ports:
            - "127.0.0.1:1984:1984"

volumes:
    filestore:
    db:
