version: "2.1"
services:
    restore_odoo:
        image: tecnativa/duplicity:postgres
        hostname: backup-odoo
        domainname: "backup"
        environment:
            DST: "file:///backups/"
            PASSPHRASE: "duppass"
            PGDATABASE: "devodoo"
            PGPASSWORD: "pgpass"
            PGUSER: "odoo"
            OPTIONS: "--force"
        volumes:
            - odoo-dev_filestore:/mnt/backup/src/odoo:z
            - ./odoo:/backups
        networks:
            - odoo-dev_default
        command: [sh, -c, "restore && mv /mnt/backup/src/odoo/filestore/prododoo /mnt/backup/src/odoo/filestore/$$PGDATABASE && createdb -T template0 $$PGDATABASE && pg_restore -d $$PGDATABASE $$SRC/prododoo.pgdump"]

networks:
    odootest_default:
        external: true

volumes:
    odootest_filestore:
        external: true